import { X, Cpu, Cloud, Network, Smartphone, Globe, Mic } from 'lucide-react';
const groups = [
  ['Normal / Basic NodeMCU', 'LED Blinking|Scrolling LED|Pushbutton LED Control|LDR Sensor Interfacing|Buzzer Tone Melody|LM35 Temperature Sensor|DHT11 Temperature & Humidity|Flame Sensor Interfacing|Ultrasonic Distance Measurement|GSM SMS Send/Receive', Cpu],
  ['ThingSpeak — Cloud/Internet', 'LM35 Monitoring via ThingSpeak|DHT11 Monitoring via ThingSpeak|Ultrasonic Monitoring via ThingSpeak|Soil Moisture Monitoring via ThingSpeak|Colour Sorting via ThingSpeak|ThingSpeak Weather Station', Cloud],
  ['Cisco Packet Tracer — Simulation', 'IoT Home Automation|IoT Smoke Detector|Pushbutton Controlled LED|IoT Devices Networking', Network],
  ['Blynk — App/Cloud', 'LED Control using Blynk|LDR Monitoring using Blynk|Smart Irrigation using Blynk|Smart Car Parking using Blynk', Smartphone],
  ['Web Server', 'Ultrasonic Water Level Web Server|LED Control via Web Page|Touchless Attendance System', Globe],
  ['Arduino IoT Cloud / Alexa', 'Smart Home using Arduino IoT Cloud|Alexa Voice-Controlled Home Automation', Mic],
] as const;
export function ExperimentCatalogue({ onClose }: { onClose: () => void }) { let n = 0; return <div className="fixed inset-0 z-[80] bg-black/70 backdrop-blur-sm p-4 sm:p-8 grid place-items-center" onClick={onClose}><div onClick={e => e.stopPropagation()} className="max-h-[88vh] w-full max-w-4xl overflow-y-auto rounded-[28px] border border-white/10 bg-[#141416] shadow-2xl"><header className="sticky top-0 z-10 flex justify-between items-start border-b border-white/10 bg-[#141416]/95 backdrop-blur p-6"><div><p className="text-xs font-bold tracking-[.16em] text-[#60a5fa]">LABORATORY RECORD</p><h2 className="mt-1 text-2xl font-bold">All 29 experiments</h2><p className="mt-1 text-sm text-[#a1a1a6]">Official record order</p></div><button onClick={onClose} className="rounded-full border border-white/10 p-2 text-[#a1a1a6] hover:text-white"><X className="w-5 h-5" /></button></header><div className="grid md:grid-cols-2 gap-4 p-6">{groups.map(([title, list, Icon]) => <section key={title} className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><div className="flex gap-3 items-center"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#0a84ff]/15 text-[#60a5fa]"><Icon className="w-4 h-4" /></span><h3 className="font-bold text-sm">{title}</h3></div><ol className="mt-4 space-y-2 text-sm text-[#d1d1d6]">{list.split('|').map(item => <li key={item} className="flex gap-3"><span className="w-5 shrink-0 font-mono text-xs text-[#60a5fa]">{String(++n).padStart(2,'0')}</span><span>{item}</span></li>)}</ol></section>)}</div></div></div> }
