-- IIoT Lab: student status, activity log and admin settings
alter table public.student_progress
  add column if not exists experiment_status jsonb not null default '{}'::jsonb;

create table if not exists public.student_activity (
  id bigint generated by default as identity primary key,
  register_number text not null,
  action text not null,
  experiment_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.student_activity enable row level security;
drop policy if exists "Anyone can read student activity" on public.student_activity;
drop policy if exists "Students can write activity" on public.student_activity;
create policy "Anyone can read student activity" on public.student_activity for select using (true);
create policy "Students can write activity" on public.student_activity for insert with check (true);

create table if not exists public.lab_settings (
  id text primary key default 'default',
  college_name text not null default 'IIoT Laboratory',
  department text not null default 'Industrial IoT Laboratory',
  academic_year text not null default '',
  footer_text text not null default '© GPTI · Made by SharanJ',
  announcements jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.lab_settings enable row level security;
drop policy if exists "Anyone can read lab settings" on public.lab_settings;
drop policy if exists "Admins manage lab settings" on public.lab_settings;
create policy "Anyone can read lab settings" on public.lab_settings for select using (true);
create policy "Admins manage lab settings" on public.lab_settings for all using (public.is_admin()) with check (public.is_admin());
insert into public.lab_settings (id) values ('default') on conflict (id) do nothing;
